version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: x86
clone_folder: c:\projects\cs16-client
environment:
  matrix:
  - project_name: client
    dll_name: client
  - project_name: mainui
    dll_name: menu
before_build:
- cmd: git submodule update --init --recursive
build:
  project: c:\projects\cs16-client\projects\%project_name%.vcxproj
  verbosity: minimal
artifacts:
- path: '**\%dll_name%.dll'
  name: '%dll_name%'
