name: adrod build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  android:
   name: Android
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - uses: actions/checkout@v3
   - uses: actions/setup-java@v3
     with:
      distribution: 'zulu'
      java-version: '8'
   - run: |
           sudo apt update
           sudo apt-get install gcc g++ clang g++-multilib gcc-multilib build-essential
           cd android/jni
           rm -rf cs-client
           ln -s ../../ ./cs-client
           cd ../
           wget -q https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
           unzip -qq android-ndk-r10e-linux-x86_64.zip
           rm -rf android-ndk-r10e-linux-x86_64.zip
           export ANDROID_NDK_HOME=android-ndk-r10e/
           ./build release noomp
   - name: Upload artifacts
     uses: actions/upload-artifact@v4
     with:
          name: adrod-libs
          path: android/libs/
